services:
  - type: web
    name: sailscan
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python sailscan.py create-db
    startCommand: gunicorn sailscan:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sailscan-db
          property: connectionString
      - key: VIRUSTOTAL_API_KEY
        sync: false
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
    domains:
      - sailscan.onrender.com

databases:
  - name: sailscan-db
    plan: free
    databaseName: sailscandb
    user: sailscanuser